site_name: Sample Documentaion Project
site_description: Sample Documentaion
site_author: Vivek Patel
site_url: https://nodesautomations.com

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Nodes Automations'

# Configuration
theme:
  name: material
    # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

   # Default values, taken from mkdocs_theme.yml
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  social:
    - type: globe
      link: https://www.nodesautomations.com
    - type: linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.tasklist

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

nav:
    - Getting started: index.md
    - Set Up : Mkdocs Documentation Setup.md
    - Admonition : Extensions/Admonition.md
    - CodeHilite : Extensions/CodeHilite.md
    - PyMarkdown  : Extensions/PyMarkdown.md

use_directory_urls: false