site_name: Sample Documentation Project
site_description: Sample Documentation
site_author: Vivek Patel
site_url: https://nodesautomations.com

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Nodes Automations'

# Configuration
theme:
  name: material
    # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

   # Default values, taken from mkdocs_theme.yml
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo
  logo: 
    icon: 'home'
  font:
    text: Roboto
    code: Roboto Mono

  
# Customization
extra:
  social:
    - type: globe
      link: https://www.nodesautomations.com
    - type: linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/

# Extensions
markdown_extensions:
  - attr_list # For Image Resize
  - markdown.extensions.admonition # For Block Style
  - markdown.extensions.codehilite: # code syntax Highlighting
      guess_lang: false
      linenums: true
  - pymdownx.caret # super Script
  - pymdownx.critic # enables the tracking of changes (additions, deletions and comments) on documents
  - pymdownx.inlinehilite # inline code highlighting
  - pymdownx.mark #Mark adds the ability to insert <mark></mark> tags for highlighting
  - pymdownx.magiclink # auto-linking HTTP, FTP and email links.
  - pymdownx.tasklist # adds GFM style task lists.
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.css
  
extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

nav:
    - Getting started: index.md
    - Set Up : Mkdocs Documentation Setup.md
    - Admonition : Extensions/Admonition.md
    - CodeHilite : Extensions/CodeHilite.md
    - PyMarkdown : Extensions/PyMarkdown.md
    - Mermaid : Extensions/mermaid.md
    - Customization : Customization.md
    - Downloads : Downloads.md

use_directory_urls: false